defaultNamespace: ghrunners-test
helm:
  #releaseName: actions-runner-controller
  chart: https://github.com/actions/actions-runner-controller/charts/actions-runner-controller
  #repo: https://github.com/actions/actions-runner-controller
  version: 0.23.7
