defaultNamespace: ghrunners-test
Helm:  
  charts:
     - charts/actions-runner-controller
     - charts/gha-runner-scale-set-controller
     - charts/gha-runner-scale-set
  repo: https://github.com/actions/actions-runner-controller
  namespace: ghr-namespace
