#defaultNamespace: ghrunners-test
helm:
  #releaseName: actions-runner-controller
  chart: actions-runner-controller
  repo: https://github.com/actions/actions-runner-controller/charts
  version: 0.23.7
