defaultNamespace: ghrunners-test
helm:
  releaseName: actions-runner-controller
  chart: charts//actions-runner-controller
  repo: git:https://github.com/actions/actions-runner-controller
  version: 0.23.7
