apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace:  actions-runner-controller
spec:
  replicas: 1
  template:
    spec:
      repository: https://git.evry.cloud/dds/infra-bix-config
